kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0005
  labels:
    foo: foo
    bar: bar
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0005/
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0006
  labels:
    foo: foo
    bar: bar
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0006/
