apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: webserver
    spec:
      containers:
      - name: webserver 
        image: 172.16.155.136:5000/uwebserverv6
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 8000
