apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver-v1
  labels:
    name: webserver
    version: v1
spec:
  replicas: 2
  selector:
    name: webserver
    version: v1
  template:
    metadata:
      labels:
        name: webserver
        version: v1
    spec:
      containers:
      - name: webserver 
        image: 172.16.155.136:5000/uwebserverv6
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: mongocluster
          value: "mongodb01, mongodb02"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: hddstorage
          mountPath: /var/etcd/data

      volumes:
      - name: hddstorage
        hostPath:
          path: /data
