apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nginxstor
spec:
  serviceName: "nginxstor"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginxstor
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      # soft antiaffinity for optimize placement
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginxstor
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginxstor
        image: 192.168.51.130:5000/uwebserverv6
        env:
          - name: SPECIAL_LEVEL_KEY
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: special.how
          - name: SPECIAL_TYPE_KEY
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: special.type
        envFrom:
        - configMapRef:
            name: hadoop-env
        ports:
          - containerPort: 8000
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 1
            memory: 512Mi

        volumeMounts:
        - mountPath: /etc/localtime
          name: hosttime
        - mountPath: /var/log/web
          name: loggerfile
      volumes:
       - name: hosttime
         hostPath:
           path: /etc/localtime 
       - name: loggerfile
         hostPath:
           path: /var/log/containerlogger/web
      #select node label if enable
      #nodeSelector:
      #  ebotrole: worker

---
apiVersion: v1
kind: Service
metadata:
  name: nginxstor
  labels:
    app: nginxstor
spec:
  ports:
  - name: http
    protocol: TCP
    #port is loadbalancer port
    port: 8001
    # targetport is container port
    targetPort: 8000
  selector:
    app: nginxstor

