apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nginxstor
spec:
  serviceName: "nginxstor"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxstor
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginxstor
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginxstor
        image: 172.16.155.136:5000/uwebserverv6
        ports:
          - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: nginxstor
  labels:
    app: nginxstor
spec:
  ports:
  - port: 8000
    name: nginxstor
  clusterIP: None
  selector:
    app: nginxstor

