apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver1
  labels:
    name: webserver1
spec:
  replicas: 1
  selector:
    name: webserver1
  template:
    metadata:
      labels:
        name: webserver1
    spec:
      containers:
      - name: webserver1 
        image: 172.16.155.136:5000/uwebserverv6
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 8000
