kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0003
  labels:
    type: fast
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0003/
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0004
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0004/
